/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTransactionsRouteRouteImport } from './routes/_auth/transactions/route'
import { Route as AuthResearchRouteRouteImport } from './routes/_auth/research/route'
import { Route as AuthNewsRouteRouteImport } from './routes/_auth/news/route'
import { Route as AuthBrokerageRouteRouteImport } from './routes/_auth/brokerage/route'
import { Route as AuthAiChatRouteRouteImport } from './routes/_auth/ai-chat/route'
import { Route as AuthAccountsRouteRouteImport } from './routes/_auth/accounts/route'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth/transactions/index'
import { Route as AuthResearchIndexRouteImport } from './routes/_auth/research/index'
import { Route as AuthNewsIndexRouteImport } from './routes/_auth/news/index'
import { Route as AuthBrokerageIndexRouteImport } from './routes/_auth/brokerage/index'
import { Route as AuthAiChatIndexRouteImport } from './routes/_auth/ai-chat/index'
import { Route as AuthAccountsIndexRouteImport } from './routes/_auth/accounts/index'
import { Route as AuthTransactionsTransactionIdRouteImport } from './routes/_auth/transactions/$transactionId'
import { Route as AuthResearchSymbolRouteImport } from './routes/_auth/research/$symbol'
import { Route as AuthNewsEventIdRouteImport } from './routes/_auth/news/$eventId'
import { Route as AuthAiChatChatIdRouteImport } from './routes/_auth/ai-chat/$chatId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionsRouteRoute = AuthTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResearchRouteRoute = AuthResearchRouteRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNewsRouteRoute = AuthNewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBrokerageRouteRoute = AuthBrokerageRouteRouteImport.update({
  id: '/brokerage',
  path: '/brokerage',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAiChatRouteRoute = AuthAiChatRouteRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountsRouteRoute = AuthAccountsRouteRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTransactionsRouteRoute,
} as any)
const AuthResearchIndexRoute = AuthResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthResearchRouteRoute,
} as any)
const AuthNewsIndexRoute = AuthNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthNewsRouteRoute,
} as any)
const AuthBrokerageIndexRoute = AuthBrokerageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBrokerageRouteRoute,
} as any)
const AuthAiChatIndexRoute = AuthAiChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAiChatRouteRoute,
} as any)
const AuthAccountsIndexRoute = AuthAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAccountsRouteRoute,
} as any)
const AuthTransactionsTransactionIdRoute =
  AuthTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AuthTransactionsRouteRoute,
  } as any)
const AuthResearchSymbolRoute = AuthResearchSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => AuthResearchRouteRoute,
} as any)
const AuthNewsEventIdRoute = AuthNewsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AuthNewsRouteRoute,
} as any)
const AuthAiChatChatIdRoute = AuthAiChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthAiChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthAccountsRouteRouteWithChildren
  '/ai-chat': typeof AuthAiChatRouteRouteWithChildren
  '/brokerage': typeof AuthBrokerageRouteRouteWithChildren
  '/news': typeof AuthNewsRouteRouteWithChildren
  '/research': typeof AuthResearchRouteRouteWithChildren
  '/transactions': typeof AuthTransactionsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/news/$eventId': typeof AuthNewsEventIdRoute
  '/research/$symbol': typeof AuthResearchSymbolRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/accounts/': typeof AuthAccountsIndexRoute
  '/ai-chat/': typeof AuthAiChatIndexRoute
  '/brokerage/': typeof AuthBrokerageIndexRoute
  '/news/': typeof AuthNewsIndexRoute
  '/research/': typeof AuthResearchIndexRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/news/$eventId': typeof AuthNewsEventIdRoute
  '/research/$symbol': typeof AuthResearchSymbolRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/accounts': typeof AuthAccountsIndexRoute
  '/ai-chat': typeof AuthAiChatIndexRoute
  '/brokerage': typeof AuthBrokerageIndexRoute
  '/news': typeof AuthNewsIndexRoute
  '/research': typeof AuthResearchIndexRoute
  '/transactions': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/accounts': typeof AuthAccountsRouteRouteWithChildren
  '/_auth/ai-chat': typeof AuthAiChatRouteRouteWithChildren
  '/_auth/brokerage': typeof AuthBrokerageRouteRouteWithChildren
  '/_auth/news': typeof AuthNewsRouteRouteWithChildren
  '/_auth/research': typeof AuthResearchRouteRouteWithChildren
  '/_auth/transactions': typeof AuthTransactionsRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_auth/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/_auth/news/$eventId': typeof AuthNewsEventIdRoute
  '/_auth/research/$symbol': typeof AuthResearchSymbolRoute
  '/_auth/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/_auth/accounts/': typeof AuthAccountsIndexRoute
  '/_auth/ai-chat/': typeof AuthAiChatIndexRoute
  '/_auth/brokerage/': typeof AuthBrokerageIndexRoute
  '/_auth/news/': typeof AuthNewsIndexRoute
  '/_auth/research/': typeof AuthResearchIndexRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/ai-chat'
    | '/brokerage'
    | '/news'
    | '/research'
    | '/transactions'
    | '/dashboard'
    | '/oauth/consent'
    | '/ai-chat/$chatId'
    | '/news/$eventId'
    | '/research/$symbol'
    | '/transactions/$transactionId'
    | '/accounts/'
    | '/ai-chat/'
    | '/brokerage/'
    | '/news/'
    | '/research/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/oauth/consent'
    | '/ai-chat/$chatId'
    | '/news/$eventId'
    | '/research/$symbol'
    | '/transactions/$transactionId'
    | '/accounts'
    | '/ai-chat'
    | '/brokerage'
    | '/news'
    | '/research'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/accounts'
    | '/_auth/ai-chat'
    | '/_auth/brokerage'
    | '/_auth/news'
    | '/_auth/research'
    | '/_auth/transactions'
    | '/_auth/dashboard'
    | '/oauth/consent'
    | '/_auth/ai-chat/$chatId'
    | '/_auth/news/$eventId'
    | '/_auth/research/$symbol'
    | '/_auth/transactions/$transactionId'
    | '/_auth/accounts/'
    | '/_auth/ai-chat/'
    | '/_auth/brokerage/'
    | '/_auth/news/'
    | '/_auth/research/'
    | '/_auth/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/research': {
      id: '/_auth/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthResearchRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/news': {
      id: '/_auth/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthNewsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/brokerage': {
      id: '/_auth/brokerage'
      path: '/brokerage'
      fullPath: '/brokerage'
      preLoaderRoute: typeof AuthBrokerageRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ai-chat': {
      id: '/_auth/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthAiChatRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/research/': {
      id: '/_auth/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof AuthResearchIndexRouteImport
      parentRoute: typeof AuthResearchRouteRoute
    }
    '/_auth/news/': {
      id: '/_auth/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof AuthNewsIndexRouteImport
      parentRoute: typeof AuthNewsRouteRoute
    }
    '/_auth/brokerage/': {
      id: '/_auth/brokerage/'
      path: '/'
      fullPath: '/brokerage/'
      preLoaderRoute: typeof AuthBrokerageIndexRouteImport
      parentRoute: typeof AuthBrokerageRouteRoute
    }
    '/_auth/ai-chat/': {
      id: '/_auth/ai-chat/'
      path: '/'
      fullPath: '/ai-chat/'
      preLoaderRoute: typeof AuthAiChatIndexRouteImport
      parentRoute: typeof AuthAiChatRouteRoute
    }
    '/_auth/accounts/': {
      id: '/_auth/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthAccountsIndexRouteImport
      parentRoute: typeof AuthAccountsRouteRoute
    }
    '/_auth/transactions/$transactionId': {
      id: '/_auth/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/research/$symbol': {
      id: '/_auth/research/$symbol'
      path: '/$symbol'
      fullPath: '/research/$symbol'
      preLoaderRoute: typeof AuthResearchSymbolRouteImport
      parentRoute: typeof AuthResearchRouteRoute
    }
    '/_auth/news/$eventId': {
      id: '/_auth/news/$eventId'
      path: '/$eventId'
      fullPath: '/news/$eventId'
      preLoaderRoute: typeof AuthNewsEventIdRouteImport
      parentRoute: typeof AuthNewsRouteRoute
    }
    '/_auth/ai-chat/$chatId': {
      id: '/_auth/ai-chat/$chatId'
      path: '/$chatId'
      fullPath: '/ai-chat/$chatId'
      preLoaderRoute: typeof AuthAiChatChatIdRouteImport
      parentRoute: typeof AuthAiChatRouteRoute
    }
  }
}

interface AuthAccountsRouteRouteChildren {
  AuthAccountsIndexRoute: typeof AuthAccountsIndexRoute
}

const AuthAccountsRouteRouteChildren: AuthAccountsRouteRouteChildren = {
  AuthAccountsIndexRoute: AuthAccountsIndexRoute,
}

const AuthAccountsRouteRouteWithChildren =
  AuthAccountsRouteRoute._addFileChildren(AuthAccountsRouteRouteChildren)

interface AuthAiChatRouteRouteChildren {
  AuthAiChatChatIdRoute: typeof AuthAiChatChatIdRoute
  AuthAiChatIndexRoute: typeof AuthAiChatIndexRoute
}

const AuthAiChatRouteRouteChildren: AuthAiChatRouteRouteChildren = {
  AuthAiChatChatIdRoute: AuthAiChatChatIdRoute,
  AuthAiChatIndexRoute: AuthAiChatIndexRoute,
}

const AuthAiChatRouteRouteWithChildren = AuthAiChatRouteRoute._addFileChildren(
  AuthAiChatRouteRouteChildren,
)

interface AuthBrokerageRouteRouteChildren {
  AuthBrokerageIndexRoute: typeof AuthBrokerageIndexRoute
}

const AuthBrokerageRouteRouteChildren: AuthBrokerageRouteRouteChildren = {
  AuthBrokerageIndexRoute: AuthBrokerageIndexRoute,
}

const AuthBrokerageRouteRouteWithChildren =
  AuthBrokerageRouteRoute._addFileChildren(AuthBrokerageRouteRouteChildren)

interface AuthNewsRouteRouteChildren {
  AuthNewsEventIdRoute: typeof AuthNewsEventIdRoute
  AuthNewsIndexRoute: typeof AuthNewsIndexRoute
}

const AuthNewsRouteRouteChildren: AuthNewsRouteRouteChildren = {
  AuthNewsEventIdRoute: AuthNewsEventIdRoute,
  AuthNewsIndexRoute: AuthNewsIndexRoute,
}

const AuthNewsRouteRouteWithChildren = AuthNewsRouteRoute._addFileChildren(
  AuthNewsRouteRouteChildren,
)

interface AuthResearchRouteRouteChildren {
  AuthResearchSymbolRoute: typeof AuthResearchSymbolRoute
  AuthResearchIndexRoute: typeof AuthResearchIndexRoute
}

const AuthResearchRouteRouteChildren: AuthResearchRouteRouteChildren = {
  AuthResearchSymbolRoute: AuthResearchSymbolRoute,
  AuthResearchIndexRoute: AuthResearchIndexRoute,
}

const AuthResearchRouteRouteWithChildren =
  AuthResearchRouteRoute._addFileChildren(AuthResearchRouteRouteChildren)

interface AuthTransactionsRouteRouteChildren {
  AuthTransactionsTransactionIdRoute: typeof AuthTransactionsTransactionIdRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthTransactionsRouteRouteChildren: AuthTransactionsRouteRouteChildren = {
  AuthTransactionsTransactionIdRoute: AuthTransactionsTransactionIdRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthTransactionsRouteRouteWithChildren =
  AuthTransactionsRouteRoute._addFileChildren(
    AuthTransactionsRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAccountsRouteRoute: typeof AuthAccountsRouteRouteWithChildren
  AuthAiChatRouteRoute: typeof AuthAiChatRouteRouteWithChildren
  AuthBrokerageRouteRoute: typeof AuthBrokerageRouteRouteWithChildren
  AuthNewsRouteRoute: typeof AuthNewsRouteRouteWithChildren
  AuthResearchRouteRoute: typeof AuthResearchRouteRouteWithChildren
  AuthTransactionsRouteRoute: typeof AuthTransactionsRouteRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountsRouteRoute: AuthAccountsRouteRouteWithChildren,
  AuthAiChatRouteRoute: AuthAiChatRouteRouteWithChildren,
  AuthBrokerageRouteRoute: AuthBrokerageRouteRouteWithChildren,
  AuthNewsRouteRoute: AuthNewsRouteRouteWithChildren,
  AuthResearchRouteRoute: AuthResearchRouteRouteWithChildren,
  AuthTransactionsRouteRoute: AuthTransactionsRouteRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
