/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthAlertsPreviewRouteImport } from './routes/_auth/alerts-preview'
import { Route as AuthTransactionsRouteRouteImport } from './routes/_auth/transactions/route'
import { Route as AuthSubscriptionsRouteRouteImport } from './routes/_auth/subscriptions/route'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthResearchRouteRouteImport } from './routes/_auth/research/route'
import { Route as AuthNewsRouteRouteImport } from './routes/_auth/news/route'
import { Route as AuthHomeRouteRouteImport } from './routes/_auth/home/route'
import { Route as AuthBrokerageRouteRouteImport } from './routes/_auth/brokerage/route'
import { Route as AuthAiChatRouteRouteImport } from './routes/_auth/ai-chat/route'
import { Route as AuthAccountsRouteRouteImport } from './routes/_auth/accounts/route'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth/transactions/index'
import { Route as AuthSubscriptionsIndexRouteImport } from './routes/_auth/subscriptions/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthResearchIndexRouteImport } from './routes/_auth/research/index'
import { Route as AuthNewsIndexRouteImport } from './routes/_auth/news/index'
import { Route as AuthHomeIndexRouteImport } from './routes/_auth/home/index'
import { Route as AuthBrokerageIndexRouteImport } from './routes/_auth/brokerage/index'
import { Route as AuthAiChatIndexRouteImport } from './routes/_auth/ai-chat/index'
import { Route as AuthAccountsIndexRouteImport } from './routes/_auth/accounts/index'
import { Route as AuthTransactionsCategoriesRouteImport } from './routes/_auth/transactions/categories'
import { Route as AuthTransactionsTransactionIdRouteImport } from './routes/_auth/transactions/$transactionId'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsBillingRouteImport } from './routes/_auth/settings/billing'
import { Route as AuthSettingsAppearanceRouteImport } from './routes/_auth/settings/appearance'
import { Route as AuthSettingsAccountRouteImport } from './routes/_auth/settings/account'
import { Route as AuthResearchSymbolRouteImport } from './routes/_auth/research/$symbol'
import { Route as AuthNewsEventIdRouteImport } from './routes/_auth/news/$eventId'
import { Route as AuthAiChatChatIdRouteImport } from './routes/_auth/ai-chat/$chatId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAlertsPreviewRoute = AuthAlertsPreviewRouteImport.update({
  id: '/alerts-preview',
  path: '/alerts-preview',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionsRouteRoute = AuthTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSubscriptionsRouteRoute = AuthSubscriptionsRouteRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResearchRouteRoute = AuthResearchRouteRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNewsRouteRoute = AuthNewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthHomeRouteRoute = AuthHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBrokerageRouteRoute = AuthBrokerageRouteRouteImport.update({
  id: '/brokerage',
  path: '/brokerage',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAiChatRouteRoute = AuthAiChatRouteRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountsRouteRoute = AuthAccountsRouteRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTransactionsRouteRoute,
} as any)
const AuthSubscriptionsIndexRoute = AuthSubscriptionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSubscriptionsRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthResearchIndexRoute = AuthResearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthResearchRouteRoute,
} as any)
const AuthNewsIndexRoute = AuthNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthNewsRouteRoute,
} as any)
const AuthHomeIndexRoute = AuthHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthHomeRouteRoute,
} as any)
const AuthBrokerageIndexRoute = AuthBrokerageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBrokerageRouteRoute,
} as any)
const AuthAiChatIndexRoute = AuthAiChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAiChatRouteRoute,
} as any)
const AuthAccountsIndexRoute = AuthAccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAccountsRouteRoute,
} as any)
const AuthTransactionsCategoriesRoute =
  AuthTransactionsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthTransactionsRouteRoute,
  } as any)
const AuthTransactionsTransactionIdRoute =
  AuthTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AuthTransactionsRouteRoute,
  } as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsBillingRoute = AuthSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsAppearanceRoute = AuthSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsAccountRoute = AuthSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthResearchSymbolRoute = AuthResearchSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => AuthResearchRouteRoute,
} as any)
const AuthNewsEventIdRoute = AuthNewsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AuthNewsRouteRoute,
} as any)
const AuthAiChatChatIdRoute = AuthAiChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthAiChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AuthAccountsRouteRouteWithChildren
  '/ai-chat': typeof AuthAiChatRouteRouteWithChildren
  '/brokerage': typeof AuthBrokerageRouteRouteWithChildren
  '/home': typeof AuthHomeRouteRouteWithChildren
  '/news': typeof AuthNewsRouteRouteWithChildren
  '/research': typeof AuthResearchRouteRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/subscriptions': typeof AuthSubscriptionsRouteRouteWithChildren
  '/transactions': typeof AuthTransactionsRouteRouteWithChildren
  '/alerts-preview': typeof AuthAlertsPreviewRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/blog/': typeof BlogIndexRoute
  '/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/news/$eventId': typeof AuthNewsEventIdRoute
  '/research/$symbol': typeof AuthResearchSymbolRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/transactions/categories': typeof AuthTransactionsCategoriesRoute
  '/accounts/': typeof AuthAccountsIndexRoute
  '/ai-chat/': typeof AuthAiChatIndexRoute
  '/brokerage/': typeof AuthBrokerageIndexRoute
  '/home/': typeof AuthHomeIndexRoute
  '/news/': typeof AuthNewsIndexRoute
  '/research/': typeof AuthResearchIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/subscriptions/': typeof AuthSubscriptionsIndexRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/alerts-preview': typeof AuthAlertsPreviewRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/blog': typeof BlogIndexRoute
  '/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/news/$eventId': typeof AuthNewsEventIdRoute
  '/research/$symbol': typeof AuthResearchSymbolRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/transactions/categories': typeof AuthTransactionsCategoriesRoute
  '/accounts': typeof AuthAccountsIndexRoute
  '/ai-chat': typeof AuthAiChatIndexRoute
  '/brokerage': typeof AuthBrokerageIndexRoute
  '/home': typeof AuthHomeIndexRoute
  '/news': typeof AuthNewsIndexRoute
  '/research': typeof AuthResearchIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/subscriptions': typeof AuthSubscriptionsIndexRoute
  '/transactions': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_auth/accounts': typeof AuthAccountsRouteRouteWithChildren
  '/_auth/ai-chat': typeof AuthAiChatRouteRouteWithChildren
  '/_auth/brokerage': typeof AuthBrokerageRouteRouteWithChildren
  '/_auth/home': typeof AuthHomeRouteRouteWithChildren
  '/_auth/news': typeof AuthNewsRouteRouteWithChildren
  '/_auth/research': typeof AuthResearchRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/subscriptions': typeof AuthSubscriptionsRouteRouteWithChildren
  '/_auth/transactions': typeof AuthTransactionsRouteRouteWithChildren
  '/_auth/alerts-preview': typeof AuthAlertsPreviewRoute
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/blog/': typeof BlogIndexRoute
  '/_auth/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/_auth/news/$eventId': typeof AuthNewsEventIdRoute
  '/_auth/research/$symbol': typeof AuthResearchSymbolRoute
  '/_auth/settings/account': typeof AuthSettingsAccountRoute
  '/_auth/settings/appearance': typeof AuthSettingsAppearanceRoute
  '/_auth/settings/billing': typeof AuthSettingsBillingRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/_auth/transactions/categories': typeof AuthTransactionsCategoriesRoute
  '/_auth/accounts/': typeof AuthAccountsIndexRoute
  '/_auth/ai-chat/': typeof AuthAiChatIndexRoute
  '/_auth/brokerage/': typeof AuthBrokerageIndexRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/news/': typeof AuthNewsIndexRoute
  '/_auth/research/': typeof AuthResearchIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/subscriptions/': typeof AuthSubscriptionsIndexRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/accounts'
    | '/ai-chat'
    | '/brokerage'
    | '/home'
    | '/news'
    | '/research'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/alerts-preview'
    | '/onboarding'
    | '/blog/$slug'
    | '/oauth/consent'
    | '/blog/'
    | '/ai-chat/$chatId'
    | '/news/$eventId'
    | '/research/$symbol'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/profile'
    | '/transactions/$transactionId'
    | '/transactions/categories'
    | '/accounts/'
    | '/ai-chat/'
    | '/brokerage/'
    | '/home/'
    | '/news/'
    | '/research/'
    | '/settings/'
    | '/subscriptions/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/alerts-preview'
    | '/onboarding'
    | '/blog/$slug'
    | '/oauth/consent'
    | '/blog'
    | '/ai-chat/$chatId'
    | '/news/$eventId'
    | '/research/$symbol'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/profile'
    | '/transactions/$transactionId'
    | '/transactions/categories'
    | '/accounts'
    | '/ai-chat'
    | '/brokerage'
    | '/home'
    | '/news'
    | '/research'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_auth/accounts'
    | '/_auth/ai-chat'
    | '/_auth/brokerage'
    | '/_auth/home'
    | '/_auth/news'
    | '/_auth/research'
    | '/_auth/settings'
    | '/_auth/subscriptions'
    | '/_auth/transactions'
    | '/_auth/alerts-preview'
    | '/_auth/onboarding'
    | '/blog/$slug'
    | '/oauth/consent'
    | '/blog/'
    | '/_auth/ai-chat/$chatId'
    | '/_auth/news/$eventId'
    | '/_auth/research/$symbol'
    | '/_auth/settings/account'
    | '/_auth/settings/appearance'
    | '/_auth/settings/billing'
    | '/_auth/settings/profile'
    | '/_auth/transactions/$transactionId'
    | '/_auth/transactions/categories'
    | '/_auth/accounts/'
    | '/_auth/ai-chat/'
    | '/_auth/brokerage/'
    | '/_auth/home/'
    | '/_auth/news/'
    | '/_auth/research/'
    | '/_auth/settings/'
    | '/_auth/subscriptions/'
    | '/_auth/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OauthConsentRoute: typeof OauthConsentRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/alerts-preview': {
      id: '/_auth/alerts-preview'
      path: '/alerts-preview'
      fullPath: '/alerts-preview'
      preLoaderRoute: typeof AuthAlertsPreviewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/subscriptions': {
      id: '/_auth/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthSubscriptionsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/research': {
      id: '/_auth/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthResearchRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/news': {
      id: '/_auth/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthNewsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/brokerage': {
      id: '/_auth/brokerage'
      path: '/brokerage'
      fullPath: '/brokerage'
      preLoaderRoute: typeof AuthBrokerageRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ai-chat': {
      id: '/_auth/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthAiChatRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/subscriptions/': {
      id: '/_auth/subscriptions/'
      path: '/'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof AuthSubscriptionsIndexRouteImport
      parentRoute: typeof AuthSubscriptionsRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/research/': {
      id: '/_auth/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof AuthResearchIndexRouteImport
      parentRoute: typeof AuthResearchRouteRoute
    }
    '/_auth/news/': {
      id: '/_auth/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof AuthNewsIndexRouteImport
      parentRoute: typeof AuthNewsRouteRoute
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthHomeIndexRouteImport
      parentRoute: typeof AuthHomeRouteRoute
    }
    '/_auth/brokerage/': {
      id: '/_auth/brokerage/'
      path: '/'
      fullPath: '/brokerage/'
      preLoaderRoute: typeof AuthBrokerageIndexRouteImport
      parentRoute: typeof AuthBrokerageRouteRoute
    }
    '/_auth/ai-chat/': {
      id: '/_auth/ai-chat/'
      path: '/'
      fullPath: '/ai-chat/'
      preLoaderRoute: typeof AuthAiChatIndexRouteImport
      parentRoute: typeof AuthAiChatRouteRoute
    }
    '/_auth/accounts/': {
      id: '/_auth/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthAccountsIndexRouteImport
      parentRoute: typeof AuthAccountsRouteRoute
    }
    '/_auth/transactions/categories': {
      id: '/_auth/transactions/categories'
      path: '/categories'
      fullPath: '/transactions/categories'
      preLoaderRoute: typeof AuthTransactionsCategoriesRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/transactions/$transactionId': {
      id: '/_auth/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/billing': {
      id: '/_auth/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthSettingsBillingRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/appearance': {
      id: '/_auth/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthSettingsAppearanceRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/research/$symbol': {
      id: '/_auth/research/$symbol'
      path: '/$symbol'
      fullPath: '/research/$symbol'
      preLoaderRoute: typeof AuthResearchSymbolRouteImport
      parentRoute: typeof AuthResearchRouteRoute
    }
    '/_auth/news/$eventId': {
      id: '/_auth/news/$eventId'
      path: '/$eventId'
      fullPath: '/news/$eventId'
      preLoaderRoute: typeof AuthNewsEventIdRouteImport
      parentRoute: typeof AuthNewsRouteRoute
    }
    '/_auth/ai-chat/$chatId': {
      id: '/_auth/ai-chat/$chatId'
      path: '/$chatId'
      fullPath: '/ai-chat/$chatId'
      preLoaderRoute: typeof AuthAiChatChatIdRouteImport
      parentRoute: typeof AuthAiChatRouteRoute
    }
  }
}

interface AuthAccountsRouteRouteChildren {
  AuthAccountsIndexRoute: typeof AuthAccountsIndexRoute
}

const AuthAccountsRouteRouteChildren: AuthAccountsRouteRouteChildren = {
  AuthAccountsIndexRoute: AuthAccountsIndexRoute,
}

const AuthAccountsRouteRouteWithChildren =
  AuthAccountsRouteRoute._addFileChildren(AuthAccountsRouteRouteChildren)

interface AuthAiChatRouteRouteChildren {
  AuthAiChatChatIdRoute: typeof AuthAiChatChatIdRoute
  AuthAiChatIndexRoute: typeof AuthAiChatIndexRoute
}

const AuthAiChatRouteRouteChildren: AuthAiChatRouteRouteChildren = {
  AuthAiChatChatIdRoute: AuthAiChatChatIdRoute,
  AuthAiChatIndexRoute: AuthAiChatIndexRoute,
}

const AuthAiChatRouteRouteWithChildren = AuthAiChatRouteRoute._addFileChildren(
  AuthAiChatRouteRouteChildren,
)

interface AuthBrokerageRouteRouteChildren {
  AuthBrokerageIndexRoute: typeof AuthBrokerageIndexRoute
}

const AuthBrokerageRouteRouteChildren: AuthBrokerageRouteRouteChildren = {
  AuthBrokerageIndexRoute: AuthBrokerageIndexRoute,
}

const AuthBrokerageRouteRouteWithChildren =
  AuthBrokerageRouteRoute._addFileChildren(AuthBrokerageRouteRouteChildren)

interface AuthHomeRouteRouteChildren {
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
}

const AuthHomeRouteRouteChildren: AuthHomeRouteRouteChildren = {
  AuthHomeIndexRoute: AuthHomeIndexRoute,
}

const AuthHomeRouteRouteWithChildren = AuthHomeRouteRoute._addFileChildren(
  AuthHomeRouteRouteChildren,
)

interface AuthNewsRouteRouteChildren {
  AuthNewsEventIdRoute: typeof AuthNewsEventIdRoute
  AuthNewsIndexRoute: typeof AuthNewsIndexRoute
}

const AuthNewsRouteRouteChildren: AuthNewsRouteRouteChildren = {
  AuthNewsEventIdRoute: AuthNewsEventIdRoute,
  AuthNewsIndexRoute: AuthNewsIndexRoute,
}

const AuthNewsRouteRouteWithChildren = AuthNewsRouteRoute._addFileChildren(
  AuthNewsRouteRouteChildren,
)

interface AuthResearchRouteRouteChildren {
  AuthResearchSymbolRoute: typeof AuthResearchSymbolRoute
  AuthResearchIndexRoute: typeof AuthResearchIndexRoute
}

const AuthResearchRouteRouteChildren: AuthResearchRouteRouteChildren = {
  AuthResearchSymbolRoute: AuthResearchSymbolRoute,
  AuthResearchIndexRoute: AuthResearchIndexRoute,
}

const AuthResearchRouteRouteWithChildren =
  AuthResearchRouteRoute._addFileChildren(AuthResearchRouteRouteChildren)

interface AuthSettingsRouteRouteChildren {
  AuthSettingsAccountRoute: typeof AuthSettingsAccountRoute
  AuthSettingsAppearanceRoute: typeof AuthSettingsAppearanceRoute
  AuthSettingsBillingRoute: typeof AuthSettingsBillingRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsAccountRoute: AuthSettingsAccountRoute,
  AuthSettingsAppearanceRoute: AuthSettingsAppearanceRoute,
  AuthSettingsBillingRoute: AuthSettingsBillingRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthSubscriptionsRouteRouteChildren {
  AuthSubscriptionsIndexRoute: typeof AuthSubscriptionsIndexRoute
}

const AuthSubscriptionsRouteRouteChildren: AuthSubscriptionsRouteRouteChildren =
  {
    AuthSubscriptionsIndexRoute: AuthSubscriptionsIndexRoute,
  }

const AuthSubscriptionsRouteRouteWithChildren =
  AuthSubscriptionsRouteRoute._addFileChildren(
    AuthSubscriptionsRouteRouteChildren,
  )

interface AuthTransactionsRouteRouteChildren {
  AuthTransactionsTransactionIdRoute: typeof AuthTransactionsTransactionIdRoute
  AuthTransactionsCategoriesRoute: typeof AuthTransactionsCategoriesRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthTransactionsRouteRouteChildren: AuthTransactionsRouteRouteChildren = {
  AuthTransactionsTransactionIdRoute: AuthTransactionsTransactionIdRoute,
  AuthTransactionsCategoriesRoute: AuthTransactionsCategoriesRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthTransactionsRouteRouteWithChildren =
  AuthTransactionsRouteRoute._addFileChildren(
    AuthTransactionsRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAccountsRouteRoute: typeof AuthAccountsRouteRouteWithChildren
  AuthAiChatRouteRoute: typeof AuthAiChatRouteRouteWithChildren
  AuthBrokerageRouteRoute: typeof AuthBrokerageRouteRouteWithChildren
  AuthHomeRouteRoute: typeof AuthHomeRouteRouteWithChildren
  AuthNewsRouteRoute: typeof AuthNewsRouteRouteWithChildren
  AuthResearchRouteRoute: typeof AuthResearchRouteRouteWithChildren
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthSubscriptionsRouteRoute: typeof AuthSubscriptionsRouteRouteWithChildren
  AuthTransactionsRouteRoute: typeof AuthTransactionsRouteRouteWithChildren
  AuthAlertsPreviewRoute: typeof AuthAlertsPreviewRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountsRouteRoute: AuthAccountsRouteRouteWithChildren,
  AuthAiChatRouteRoute: AuthAiChatRouteRouteWithChildren,
  AuthBrokerageRouteRoute: AuthBrokerageRouteRouteWithChildren,
  AuthHomeRouteRoute: AuthHomeRouteRouteWithChildren,
  AuthNewsRouteRoute: AuthNewsRouteRouteWithChildren,
  AuthResearchRouteRoute: AuthResearchRouteRouteWithChildren,
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthSubscriptionsRouteRoute: AuthSubscriptionsRouteRouteWithChildren,
  AuthTransactionsRouteRoute: AuthTransactionsRouteRouteWithChildren,
  AuthAlertsPreviewRoute: AuthAlertsPreviewRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  OauthConsentRoute: OauthConsentRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
