/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResearchRouteImport } from './routes/_auth/research'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthBrokerageRouteImport } from './routes/_auth/brokerage'
import { Route as AuthAccountsRouteImport } from './routes/_auth/accounts'
import { Route as AuthTransactionsRouteRouteImport } from './routes/_auth/transactions/route'
import { Route as AuthAiChatRouteRouteImport } from './routes/_auth/ai-chat/route'
import { Route as AuthTransactionsIndexRouteImport } from './routes/_auth/transactions/index'
import { Route as AuthAiChatIndexRouteImport } from './routes/_auth/ai-chat/index'
import { Route as AuthTransactionsTransactionIdRouteImport } from './routes/_auth/transactions/$transactionId'
import { Route as AuthAiChatChatIdRouteImport } from './routes/_auth/ai-chat/$chatId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResearchRoute = AuthResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthBrokerageRoute = AuthBrokerageRouteImport.update({
  id: '/brokerage',
  path: '/brokerage',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccountsRoute = AuthAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionsRouteRoute = AuthTransactionsRouteRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAiChatRouteRoute = AuthAiChatRouteRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransactionsIndexRoute = AuthTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTransactionsRouteRoute,
} as any)
const AuthAiChatIndexRoute = AuthAiChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAiChatRouteRoute,
} as any)
const AuthTransactionsTransactionIdRoute =
  AuthTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AuthTransactionsRouteRoute,
  } as any)
const AuthAiChatChatIdRoute = AuthAiChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthAiChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-chat': typeof AuthAiChatRouteRouteWithChildren
  '/transactions': typeof AuthTransactionsRouteRouteWithChildren
  '/accounts': typeof AuthAccountsRoute
  '/brokerage': typeof AuthBrokerageRoute
  '/dashboard': typeof AuthDashboardRoute
  '/research': typeof AuthResearchRoute
  '/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/ai-chat/': typeof AuthAiChatIndexRoute
  '/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthAccountsRoute
  '/brokerage': typeof AuthBrokerageRoute
  '/dashboard': typeof AuthDashboardRoute
  '/research': typeof AuthResearchRoute
  '/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/ai-chat': typeof AuthAiChatIndexRoute
  '/transactions': typeof AuthTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/ai-chat': typeof AuthAiChatRouteRouteWithChildren
  '/_auth/transactions': typeof AuthTransactionsRouteRouteWithChildren
  '/_auth/accounts': typeof AuthAccountsRoute
  '/_auth/brokerage': typeof AuthBrokerageRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/research': typeof AuthResearchRoute
  '/_auth/ai-chat/$chatId': typeof AuthAiChatChatIdRoute
  '/_auth/transactions/$transactionId': typeof AuthTransactionsTransactionIdRoute
  '/_auth/ai-chat/': typeof AuthAiChatIndexRoute
  '/_auth/transactions/': typeof AuthTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-chat'
    | '/transactions'
    | '/accounts'
    | '/brokerage'
    | '/dashboard'
    | '/research'
    | '/ai-chat/$chatId'
    | '/transactions/$transactionId'
    | '/ai-chat/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/brokerage'
    | '/dashboard'
    | '/research'
    | '/ai-chat/$chatId'
    | '/transactions/$transactionId'
    | '/ai-chat'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/ai-chat'
    | '/_auth/transactions'
    | '/_auth/accounts'
    | '/_auth/brokerage'
    | '/_auth/dashboard'
    | '/_auth/research'
    | '/_auth/ai-chat/$chatId'
    | '/_auth/transactions/$transactionId'
    | '/_auth/ai-chat/'
    | '/_auth/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/research': {
      id: '/_auth/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthResearchRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/brokerage': {
      id: '/_auth/brokerage'
      path: '/brokerage'
      fullPath: '/brokerage'
      preLoaderRoute: typeof AuthBrokerageRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ai-chat': {
      id: '/_auth/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthAiChatRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transactions/': {
      id: '/_auth/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthTransactionsIndexRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/ai-chat/': {
      id: '/_auth/ai-chat/'
      path: '/'
      fullPath: '/ai-chat/'
      preLoaderRoute: typeof AuthAiChatIndexRouteImport
      parentRoute: typeof AuthAiChatRouteRoute
    }
    '/_auth/transactions/$transactionId': {
      id: '/_auth/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthTransactionsRouteRoute
    }
    '/_auth/ai-chat/$chatId': {
      id: '/_auth/ai-chat/$chatId'
      path: '/$chatId'
      fullPath: '/ai-chat/$chatId'
      preLoaderRoute: typeof AuthAiChatChatIdRouteImport
      parentRoute: typeof AuthAiChatRouteRoute
    }
  }
}

interface AuthAiChatRouteRouteChildren {
  AuthAiChatChatIdRoute: typeof AuthAiChatChatIdRoute
  AuthAiChatIndexRoute: typeof AuthAiChatIndexRoute
}

const AuthAiChatRouteRouteChildren: AuthAiChatRouteRouteChildren = {
  AuthAiChatChatIdRoute: AuthAiChatChatIdRoute,
  AuthAiChatIndexRoute: AuthAiChatIndexRoute,
}

const AuthAiChatRouteRouteWithChildren = AuthAiChatRouteRoute._addFileChildren(
  AuthAiChatRouteRouteChildren,
)

interface AuthTransactionsRouteRouteChildren {
  AuthTransactionsTransactionIdRoute: typeof AuthTransactionsTransactionIdRoute
  AuthTransactionsIndexRoute: typeof AuthTransactionsIndexRoute
}

const AuthTransactionsRouteRouteChildren: AuthTransactionsRouteRouteChildren = {
  AuthTransactionsTransactionIdRoute: AuthTransactionsTransactionIdRoute,
  AuthTransactionsIndexRoute: AuthTransactionsIndexRoute,
}

const AuthTransactionsRouteRouteWithChildren =
  AuthTransactionsRouteRoute._addFileChildren(
    AuthTransactionsRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAiChatRouteRoute: typeof AuthAiChatRouteRouteWithChildren
  AuthTransactionsRouteRoute: typeof AuthTransactionsRouteRouteWithChildren
  AuthAccountsRoute: typeof AuthAccountsRoute
  AuthBrokerageRoute: typeof AuthBrokerageRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthResearchRoute: typeof AuthResearchRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAiChatRouteRoute: AuthAiChatRouteRouteWithChildren,
  AuthTransactionsRouteRoute: AuthTransactionsRouteRouteWithChildren,
  AuthAccountsRoute: AuthAccountsRoute,
  AuthBrokerageRoute: AuthBrokerageRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthResearchRoute: AuthResearchRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
