import type { TransactionListItem } from "@cobalt-web/server-data/transactions/schemas";

/** Seed rows — expanded below to fill the page for layout work. */
const MOCK_TRANSACTION_SEED: TransactionListItem[] = [
  {
    accountName: "Checking ···4821",
    accountType: "depository",
    amount: -84.25,
    authorizedDate: "2025-03-23",
    date: "2025-03-24",
    id: "a0000001-0000-4000-8000-000000000001",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Whole Foods Market",
    name: "WHOLE FOODS MKT #12345",
    pending: false,
    personalFinanceCategory: {
      detailed: "FOOD_AND_DRINK_GROCERIES",
      primary: "FOOD_AND_DRINK",
    },
    plaidAccountId: "plaid-acc-checking-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Checking ···4821",
    accountType: "depository",
    amount: 3250,
    authorizedDate: null,
    date: "2025-03-23",
    id: "a0000001-0000-4000-8000-000000000002",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Employer Payroll",
    name: "DIRECT DEP EMPLOYER PAYROLL",
    pending: false,
    personalFinanceCategory: {
      detailed: "INCOME_PAYROLL",
      primary: "INCOME",
    },
    plaidAccountId: "plaid-acc-checking-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -48,
    authorizedDate: null,
    date: "2025-03-23",
    id: "a0000001-0000-4000-8000-000000000003",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Shell",
    name: "SHELL OIL 12345",
    pending: false,
    personalFinanceCategory: {
      detailed: "TRANSPORTATION_GAS",
      primary: "TRANSPORTATION",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -15.99,
    authorizedDate: null,
    date: "2025-03-22",
    id: "a0000001-0000-4000-8000-000000000004",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Netflix",
    name: "NETFLIX.COM",
    pending: false,
    personalFinanceCategory: {
      detailed: "ENTERTAINMENT_MUSIC_AND_VIDEO_STREAMING",
      primary: "ENTERTAINMENT",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -67.33,
    authorizedDate: null,
    date: "2025-03-22",
    id: "a0000001-0000-4000-8000-000000000005",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Amazon",
    name: "AMZN Mktp US",
    pending: true,
    personalFinanceCategory: {
      detailed: "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES",
      primary: "GENERAL_MERCHANDISE",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -6.25,
    authorizedDate: null,
    date: "2025-03-21",
    id: "a0000001-0000-4000-8000-000000000006",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Blue Bottle Coffee",
    name: "BLUE BOTTLE COFFEE",
    pending: false,
    personalFinanceCategory: {
      detailed: "FOOD_AND_DRINK_COFFEE",
      primary: "FOOD_AND_DRINK",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -28.4,
    authorizedDate: null,
    date: "2025-03-20",
    id: "a0000001-0000-4000-8000-000000000007",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Uber",
    name: "UBER TRIP",
    pending: false,
    personalFinanceCategory: {
      detailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
      primary: "TRANSPORTATION",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Checking ···4821",
    accountType: "depository",
    amount: -500,
    authorizedDate: null,
    date: "2025-03-20",
    id: "a0000001-0000-4000-8000-000000000008",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: null,
    name: "TRANSFER TO SAVINGS XXXXX",
    pending: false,
    personalFinanceCategory: {
      detailed: "TRANSFER_OUT_SAVINGS",
      primary: "TRANSFER_OUT",
    },
    plaidAccountId: "plaid-acc-checking-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Checking ···4821",
    accountType: "depository",
    amount: -124.5,
    authorizedDate: null,
    date: "2025-03-19",
    id: "a0000001-0000-4000-8000-000000000009",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "PG&E",
    name: "PG&E BILL PAY",
    pending: false,
    personalFinanceCategory: {
      detailed: "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
      primary: "RENT_AND_UTILITIES",
    },
    plaidAccountId: "plaid-acc-checking-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -112.08,
    authorizedDate: null,
    date: "2025-03-18",
    id: "a0000001-0000-4000-8000-000000000010",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Target",
    name: "TARGET T-1234",
    pending: false,
    personalFinanceCategory: {
      detailed: "GENERAL_MERCHANDISE_DEPARTMENT_STORES",
      primary: "GENERAL_MERCHANDISE",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Savings ···7730",
    accountType: "depository",
    amount: 4.12,
    authorizedDate: null,
    date: "2025-03-17",
    id: "a0000001-0000-4000-8000-000000000011",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: null,
    name: "INTEREST PAYMENT",
    pending: false,
    personalFinanceCategory: {
      detailed: "INCOME_INTEREST_EARNED",
      primary: "INCOME",
    },
    plaidAccountId: "plaid-acc-savings-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -10.99,
    authorizedDate: null,
    date: "2025-03-16",
    id: "a0000001-0000-4000-8000-000000000012",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Spotify",
    name: "SPOTIFY USA",
    pending: false,
    personalFinanceCategory: {
      detailed: "ENTERTAINMENT_MUSIC_AND_AUDIO",
      primary: "ENTERTAINMENT",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -56.12,
    authorizedDate: null,
    date: "2025-03-15",
    id: "a0000001-0000-4000-8000-000000000013",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Trader Joe's",
    name: "TRADER JOES #999",
    pending: false,
    personalFinanceCategory: {
      detailed: "FOOD_AND_DRINK_GROCERIES",
      primary: "FOOD_AND_DRINK",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Checking ···4821",
    accountType: "depository",
    amount: -200,
    authorizedDate: null,
    date: "2025-03-14",
    id: "a0000001-0000-4000-8000-000000000014",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: null,
    name: "ATM WITHDRAWAL",
    pending: false,
    personalFinanceCategory: {
      detailed: "BANK_FEES_ATM_FEES",
      primary: "BANK_FEES",
    },
    plaidAccountId: "plaid-acc-checking-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
  {
    accountName: "Credit ···9012",
    accountType: "credit",
    amount: -428.9,
    authorizedDate: null,
    date: "2025-03-13",
    id: "a0000001-0000-4000-8000-000000000015",
    institutionLogo: null,
    institutionName: "Chase",
    institutionUrl: "https://www.chase.com",
    location: null,
    logoUrl: null,
    merchantName: "Delta Air Lines",
    name: "DELTA AIR",
    pending: true,
    personalFinanceCategory: {
      detailed: "TRAVEL_FLIGHTS",
      primary: "TRAVEL",
    },
    plaidAccountId: "plaid-acc-credit-1",
    userOverrideCategory: null,
    userOverrideDate: null,
    userOverrideName: null,
  },
];

function shiftIsoDate(iso: string, daysBack: number): string {
  const d = new Date(`${iso}T12:00:00.000Z`);
  d.setUTCDate(d.getUTCDate() - daysBack);
  return d.toISOString().slice(0, 10);
}

/** ~75 rows: repeated seed with shifted dates / ids so the list scrolls the full viewport. */
export const MOCK_TRANSACTIONS: TransactionListItem[] = (() => {
  const cycles = 5;
  const out: TransactionListItem[] = [];
  for (let c = 0; c < cycles; c += 1) {
    for (let i = 0; i < MOCK_TRANSACTION_SEED.length; i += 1) {
      const row = MOCK_TRANSACTION_SEED[i];
      const dayOffset = c * 20 + i;
      const dateStr = shiftIsoDate(row.date, dayOffset);
      const authorizedDateStr = row.authorizedDate
        ? shiftIsoDate(row.authorizedDate, dayOffset)
        : null;
      const idSuffix = (c * 100 + i).toString(16).padStart(12, "0");
      out.push({
        ...row,
        amount:
          Math.round(row.amount * (1 + c * 0.012 + i * 0.001) * 100) / 100,
        authorizedDate: authorizedDateStr,
        date: dateStr,
        id: `00000000-0000-4000-8000-${idSuffix}`,
        pending: c === 0 ? row.pending : false,
      });
    }
  }
  out.sort((a, b) => b.date.localeCompare(a.date));
  return out;
})();
