import { env } from "@cobalt-web/env/server";
import { TOPIC_CATEGORIES } from "@cobalt-web/server-data/news/events/lib";
import type {
  EventSummary,
  ProcessedArticle,
  TopicCategory,
} from "@cobalt-web/server-data/news/events/lib";
import { generateText, NoObjectGeneratedError, NoOutputGeneratedError, Output } from "ai";
import { z } from "zod";

import { gatewayModel } from "../../model-provider.js";

const SUMMARY_MODEL = "google/gemini-2.5-flash";
const MAX_TOKENS = 3000;
const TEMPERATURE = 0.3;

const eventSummarySchema = z.object({
  eventSummary: z.string(),
  keyPoints: z.array(z.string()).max(8).default([]),
  overallSentiment: z.enum(["positive", "negative", "neutral"]),
  topics: z.array(z.enum(TOPIC_CATEGORIES)).min(1),
});

// Transient-failure signal for the calling workflow step. The step catches
// this, translates it to `RetryableError`, and owns the backoff policy
// (currently exponential via `getStepMetadata()`). The agent stays
// framework-free (matches the chat-title pattern).
export class TransientSummaryError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TransientSummaryError";
  }
}

function formatArticle(article: ProcessedArticle, index: number): string {
  const orig = article.originalArticle;
  const imgLine = orig.image_url ? `Image: ${orig.image_url}\n` : "";
  return `Article ${index + 1}: ${orig.title}
Source: ${orig.source_name}
Type: ${orig.type}
Author: ${article.extractedContent.author ?? "Unknown"}
Published: ${article.extractedContent.publishedTime ?? "Unknown"}
URL: ${orig.news_url}
${imgLine}
Content:
${article.extractedContent.text}

---`;
}

/**
 * Generate a structured summary of a financial event from its scraped article
 * bundle. Pure agent: one LLM call via the AI Gateway, Zod-validated output,
 * no workflow/retry semantics — callers (a step, a script) translate the
 * `TransientSummaryError` signal into their own retry policy.
 */
export async function summarizeEventArticles(
  eventName: string,
  eventText: string | undefined,
  articles: ProcessedArticle[],
): Promise<EventSummary> {
  const start = Date.now();

  if (articles.length === 0) {
    throw new Error("No articles to summarize");
  }
  if (!env.AI_GATEWAY_API_KEY) {
    throw new Error("AI_GATEWAY_API_KEY not configured");
  }

  const hasVideo = articles.some((a) => a.originalArticle.type.toLowerCase() === "video");

  const prompt = `Write a concise, Perplexity-style markdown article about "${eventName}" grounded strictly in the provided source articles.

Event Description: ${eventText ?? "No description available"}
${hasVideo ? "\nNOTE: This event includes video content - reference video-specific information where relevant." : ""}

Source Articles (1-indexed):
${articles.map((a, i) => formatArticle(a, i)).join("\n")}

OUTPUT REQUIREMENTS — produce four fields:

1. eventSummary — a markdown article. Strict format:
   - 2 to 4 sections, each starting with a "##" heading. Pick descriptive section titles based on the actual content (not generic headers like "Background" or "Overview" unless that genuinely fits).
   - Each section: 1-2 tight paragraphs. No walls of text. No bullet lists.
   - Inline citations as markdown links with the hash URL "#cite-N", where N is the 1-indexed source article. Format: [N](#cite-N).
   - Place citations at the END of the relevant sentence or paragraph. Cite every factual claim. Cluster multiple sources at the same location when they corroborate the same fact: "...announced layoffs [1](#cite-1)[3](#cite-3)[5](#cite-5)."
   - Use ONLY citation indices that exist in the source list above. Never fabricate.
   - Do NOT include a "## Sources" section, raw URLs, or footnotes — the UI renders sources separately.
   - Do NOT include the event name as a top-level "#" heading — that is also rendered separately by the UI.

2. keyPoints — leave empty array. (Deprecated; kept for back-compat.)

3. overallSentiment — "positive", "negative", or "neutral".

4. topics — one or more of: tech, government, analyst, AI, announcement, leadership, energy, earnings, other.

Stay strictly factual. No predictions, no investment advice. Quote sparingly; paraphrase by default.`;

  try {
    const result = await generateText({
      experimental_telemetry: {
        functionId: "financial-events-summary-agent",
        isEnabled: true,
      },
      maxOutputTokens: MAX_TOKENS,
      model: gatewayModel(SUMMARY_MODEL),
      output: Output.object({ schema: eventSummarySchema }),
      prompt,
      temperature: TEMPERATURE,
    });

    if (!result.output) {
      throw new TransientSummaryError("No output generated by AI model");
    }

    const topics: TopicCategory[] =
      result.output.topics.length > 0 ? result.output.topics : ["other"];

    return {
      articleCount: articles.length,
      eventSummary: result.output.eventSummary || "Event summary not available",
      keyPoints: result.output.keyPoints ?? [],
      overallSentiment: result.output.overallSentiment ?? "neutral",
      processingMetadata: {
        model: SUMMARY_MODEL,
        processingTime: Date.now() - start,
        success: true,
        summarizedAt: new Date(),
      },
      topics,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    if (error instanceof TransientSummaryError) {
      throw error;
    }
    if (
      NoObjectGeneratedError.isInstance(error) ||
      NoOutputGeneratedError.isInstance(error) ||
      /did not match schema|No object generated|No output generated/i.test(message)
    ) {
      throw new TransientSummaryError(`AI output error: ${message}`);
    }
    if (/rate limit|timeout|network|ECONNRESET|ETIMEDOUT/i.test(message)) {
      throw new TransientSummaryError(`Transient error: ${message}`);
    }

    return {
      articleCount: 0,
      eventSummary: "Event summary generation failed",
      keyPoints: [],
      overallSentiment: "neutral",
      processingMetadata: {
        error: message,
        model: SUMMARY_MODEL,
        processingTime: Date.now() - start,
        success: false,
        summarizedAt: new Date(),
      },
      topics: ["other"],
    };
  }
}
