import { env } from "@cobalt-web/env/server";
import { TOPIC_CATEGORIES } from "@cobalt-web/server-data/news/events/lib";
import type {
  EventSummary,
  ProcessedArticle,
  TopicCategory,
} from "@cobalt-web/server-data/news/events/lib";
import { generateText, NoObjectGeneratedError, NoOutputGeneratedError, Output } from "ai";
import { z } from "zod";

import { gatewayModel } from "../../model-provider.js";

const SUMMARY_MODEL = "google/gemini-2.5-flash";
const MAX_TOKENS = 2000;
const TEMPERATURE = 0.3;

const eventSummarySchema = z.object({
  eventSummary: z.string(),
  keyPoints: z.array(z.string()).min(4).max(6),
  overallSentiment: z.enum(["positive", "negative", "neutral"]),
  topics: z.array(z.enum(TOPIC_CATEGORIES)).min(1),
});

// Transient-failure signal for the calling workflow step. The step catches
// this, translates it to `RetryableError`, and owns the backoff policy
// (currently exponential via `getStepMetadata()`). The agent stays
// framework-free (matches the chat-title pattern).
export class TransientSummaryError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TransientSummaryError";
  }
}

function formatArticle(article: ProcessedArticle, index: number): string {
  const orig = article.originalArticle;
  const imgLine = orig.image_url ? `Image: ${orig.image_url}\n` : "";
  return `Article ${index + 1}: ${orig.title}
Source: ${orig.source_name}
Type: ${orig.type}
Author: ${article.extractedContent.author ?? "Unknown"}
Published: ${article.extractedContent.publishedTime ?? "Unknown"}
URL: ${orig.news_url}
${imgLine}
Content:
${article.extractedContent.text}

---`;
}

/**
 * Generate a structured summary of a financial event from its scraped article
 * bundle. Pure agent: one LLM call via the AI Gateway, Zod-validated output,
 * no workflow/retry semantics — callers (a step, a script) translate the
 * `TransientSummaryError` signal into their own retry policy.
 */
export async function summarizeEventArticles(
  eventName: string,
  eventText: string | undefined,
  articles: ProcessedArticle[],
): Promise<EventSummary> {
  const start = Date.now();

  if (articles.length === 0) {
    throw new Error("No articles to summarize");
  }
  if (!env.AI_GATEWAY_API_KEY) {
    throw new Error("AI_GATEWAY_API_KEY not configured");
  }

  const hasVideo = articles.some((a) => a.originalArticle.type.toLowerCase() === "video");

  const prompt = `Analyze these financial news articles about "${eventName}" and provide a comprehensive, factual analysis based on the information provided.

Event Description: ${eventText ?? "No description available"}
${hasVideo ? "\nNOTE: This event includes video content - please highlight any video-specific information in your analysis." : ""}

Articles to Analyze:
${articles.map((a, i) => formatArticle(a, i)).join("\n")}

Please provide:
1. Executive Summary — 3-4 paragraphs grounded in the article text.
2. Key Analysis Points — 4-6 detailed points covering metrics, announcements, analyst opinions, or context mentioned in the articles.
3. Overall Sentiment — positive, negative, or neutral.
4. Topics — one or more of: tech, government, analyst, AI, announcement, leadership, energy, earnings, other.

Stay strictly factual. No predictions, no investment advice.`;

  try {
    const result = await generateText({
      experimental_telemetry: {
        functionId: "financial-events-summary-agent",
        isEnabled: true,
      },
      maxOutputTokens: MAX_TOKENS,
      model: gatewayModel(SUMMARY_MODEL),
      output: Output.object({ schema: eventSummarySchema }),
      prompt,
      temperature: TEMPERATURE,
    });

    if (!result.output) {
      throw new TransientSummaryError("No output generated by AI model");
    }

    const topics: TopicCategory[] =
      result.output.topics.length > 0 ? result.output.topics : ["other"];

    return {
      articleCount: articles.length,
      eventSummary: result.output.eventSummary || "Event summary not available",
      keyPoints: result.output.keyPoints ?? [],
      overallSentiment: result.output.overallSentiment ?? "neutral",
      processingMetadata: {
        model: SUMMARY_MODEL,
        processingTime: Date.now() - start,
        success: true,
        summarizedAt: new Date(),
      },
      topics,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    if (error instanceof TransientSummaryError) {
      throw error;
    }
    if (
      NoObjectGeneratedError.isInstance(error) ||
      NoOutputGeneratedError.isInstance(error) ||
      /did not match schema|No object generated|No output generated/i.test(message)
    ) {
      throw new TransientSummaryError(`AI output error: ${message}`);
    }
    if (/rate limit|timeout|network|ECONNRESET|ETIMEDOUT/i.test(message)) {
      throw new TransientSummaryError(`Transient error: ${message}`);
    }

    return {
      articleCount: 0,
      eventSummary: "Event summary generation failed",
      keyPoints: [],
      overallSentiment: "neutral",
      processingMetadata: {
        error: message,
        model: SUMMARY_MODEL,
        processingTime: Date.now() - start,
        success: false,
        summarizedAt: new Date(),
      },
      topics: ["other"],
    };
  }
}
