#!/usr/bin/env bun
// Bundles `src/stdlib-entry.ts` into a minified IIFE and writes it as a
// TypeScript string constant at `src/stdlib-bundle.ts`. The bundle is then
// prepended to user code inside the V8 isolate sandbox so calc helpers
// (`cobalt.calc.*`) are callable without an RPC round-trip.
//
// Run manually via `bun run build:stdlib` whenever `stdlib-entry.ts` or any
// of its dependencies (e.g. `financial`) changes. CI should run this as part
// of the build step before type-check / test.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const entry = join(here, "../src/stdlib-entry.ts");
const outFile = join(here, "../src/stdlib-bundle.ts");

const result = await Bun.build({
  entrypoints: [entry],
  format: "iife",
  minify: true,
  target: "browser",
});

if (!result.success) {
  for (const log of result.logs) {
    console.error(log);
  }
  process.exit(1);
}

const code = await result.outputs[0]?.text();
if (!code) {
  console.error("build produced no output");
  process.exit(1);
}

const header = `// AUTO-GENERATED by scripts/build-stdlib.ts — do not edit by hand.
// Re-run \`bun run build:stdlib\` from \`packages/bindings\` to regenerate.
`;

writeFileSync(outFile, `${header}export const STDLIB_BUNDLE = ${JSON.stringify(code)};\n`);
console.log(`wrote stdlib-bundle.ts (${code.length} bytes minified)`);
