import {
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const SRC = join(SCRIPT_DIR, "../../../packages/db/src");
const OUT = join(SCRIPT_DIR, "../src/ai/agents/code-agent/schema-files.gen.ts");

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files: Record<string, string> = {};
for (const path of walk(SRC)) {
  if (!path.endsWith(".ts")) {
    continue;
  }
  const rel = relative(SRC, path);
  files[rel] = readFileSync(path, "utf-8");
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Auto-generated by scripts/gen-schema-files.ts. Do not edit.\nexport const schemaFiles: Record<string, string> = ${JSON.stringify(
    files,
    null,
    2
  )};\n`
);

console.log(
  `[gen-schema-files] wrote ${String(Object.keys(files).length)} files to ${relative(process.cwd(), OUT)}`
);
